export interface Data {
    id: number;
    name: string;
    image: string;
    route: string;
    sacco: string;
    seats: number;
}

export default function matatus() {
    return [
        {
            id: 1,
            name: "Opposite - Manunda",
            image: "/opposite.png",
            route: "Umoja",
            sacco: "Umoinner",
            seats: 33,
        },
        {
            id: 2,
            name: "Moxie",
            image: "/moxie.png",
            route: "Rongai",
            sacco: "R.O.G",
            seats: 33,
        },
        {
            id: 1,
            name: "Moneyfest",
            image: "/moneyfest.png",
            route: "Emba",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "BrawlOut",
            image: "/brawl.png",
            route: "Emba Pesa",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "Dice",
            image: "/dice.png",
            route: "Emba Pesa",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "JohnWick - Babayaga",
            image: "/babayaga.png",
            route: "Rongai",
            sacco: "R.O.G",
            seats: 33,
        },
        {
            id: 1,
            name: "Uppercut - Makmende",
            image: "/uppercut.png",
            route: "Emba",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "x-rated",
            image: "/xrated.png",
            route: "Ngong",
            sacco: "Ngong",
            seats: 33,
        },
        {
            id: 1,
            name: "Cycology",
            image: "/cycology.png",
            route: "Rongai",
            sacco: "R.O.G",
            seats: 33,
        },
        {
            id: 1,
            name: "Dethrone",
            image: "/dethrone.png",
            route: "Kiambu",
            sacco: "Kiambu",
            seats: 33,
        },
        {
            id: 1,
            name: "G-Unit",
            image: "/gunit.png",
            route: "Rongai",
            sacco: "R.O.G",
            seats: 33,
        },
        {
            id: 1,
            name: "Detox",
            image: "/detox.png",
            route: "Umoja",
            sacco: "umoja",
            seats: 33,
        },
        {
            id: 1,
            name: "Fortune",
            image: "/fortune.png",
            route: "Ngong",
            sacco: "Ngong",
            seats: 33,
        },
        {
            id: 1,
            name: "Harukaze",
            image: "/harukaze.png",
            route: "Ngong",
            sacco: "Ngong",
            seats: 33,
        },
        {
            id: 1,
            name: "Heartless",
            image: "/heartless1.png",
            route: "Emba",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "Jabari",
            image: "/jabari.png",
            route: "Kasarani",
            sacco: "Kasarani",
            seats: 33,
        },
        {
            id: 1,
            name: "Matrix",
            image: "/matrix.png",
            route: "Emba",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "No-Fear - Kasongo",
            image: "/nofear.png",
            route: "Kibera",
            sacco: "Kibera",
            seats: 33,
        },
        {
            id: 1,
            name: "Phenomenal",
            image: "/phenomenal.png",
            route: "Ngong",
            sacco: "Ngong",
            seats: 33,
        },
        {
            id: 1,
            name: "Plank",
            image: "/plank.png",
            route: "Umoja",
            sacco: "Umoja",
            seats: 33,
        },
        {
            id: 1,
            name: "Restoration",
            image: "/restoration.png",
            route: "Emba",
            sacco: "Emba",
            seats: 33,
        },
        {
            id: 1,
            name: "Spice",
            image: "/spice.png",
            route: "Ngong",
            sacco: "Ngong",
            seats: 33,
        },
        {
            id: 1,
            name: "Subzero",
            image: "/subzero.png",
            route: "Kiambu",
            sacco: "Kiambu",
            seats: 33,
        },
       
    ]
};